### ISSUE TITLE
Remove the commenter in the form

### ISSUE THREAD

**Issue by YEthYuan** [YEthYuan/UCSBCS291AProject3#3]
Due to the use of a session, people do not need to input their names when sending a comment. We should remove the commenter field in the form and set up the session on comments

**Comment by AndyCheng2** [comment]
finsh with the commit: [feat: comment without input user](https://github.com/YEthYuan/UCSBCS291AProject3/commit/1fda049f3b8dd058c32b4e2b8298c2bb5653c067)
